woowa-techcamp-2021/cashbook-18

client/src/Components/Header/index.ts
client/src/Core/Component.ts
client/src/Core/Router.ts
client/src/Model/TodoModel.ts
client/src/View/Calendar/index.ts
client/src/View/Charts/index.ts
client/src/View/Home/index.ts
client/src/View/Main/index.ts
client/src/View/Main/styles.scss
client/src/main.ts
client/src/utils/types.ts

- 컴포넌트가 해제되는 시점을 감지하는 unmount 관련 메서드 추가
- 관련 임시로 `any`로 지정된 타입 재지정 (전부 진행하지는 못함)
- 타입 추가로 인해 컴포넌트 사용 방식이 살짝 변경됨 (타입만 추가하면 됩니다)

[refactor] Component 클래스 unmount 이벤트 메서드 추가

---

client/src/Components/CategoryTag/index.ts
client/src/Components/Header/index.ts
client/src/Components/HistoryDayCard/index.ts
client/src/Components/List/index.ts
client/src/Components/List/styles.scss
client/src/Components/Main/index.ts
client/src/Components/Main/styles.scss
client/src/Core/Component.ts
client/src/Model/MainModel.ts
client/src/View/MainView/index.ts
client/src/View/MainView/styles.scss
client/src/assets/svgIcons.ts
client/src/utils/types.ts

관련 이슈 : #5 
* 완료 버튼을 추가하여 history 리스트를 업데이트할 수 있습니다(아직 validation은 안된 상태)
* history를 현재 달에 해당하는 데이터로만 가져와 오름차순으로 정렬하였습니다.
* 수입/지출 버튼을 선택하여 history를 출력하게 하였습니다.
* 수입/지출 총 금액 계산하였습니다.
* addEvent에서 콜백 함수에 Event 객체가 전달이 안되는 버그 수정하였씁니다.
* 여러 개의 모델을 구독하는데 그 모델들의 순서가 중요한 경우, 여러 문제가 발생하여서 일단 event에서 해당 notify를 처리하는 방식으로 진행했습니다.

[feature] 메인 페이지 기능 추가

---

script/deploy.sh

* it closes #27 
쉘 스크립트 추가하고 서버에서 crontab 설정하였씁니당
http://ec2-3-34-193-180.ap-northeast-2.compute.amazonaws.com/
[참고](https://github.com/woowa-techcamp-2021/cashbook-18/wiki/%EC%84%9C%EB%B2%84-%EC%9E%90%EB%8F%99-%EB%B0%B0%ED%8F%AC:-sh-script%EC%99%80-crontab)

[#27] chore: 서버 자동 배포 스크립트 추가

---

client/src/View/MainView/index.ts
client/src/View/MainView/styles.scss
client/src/utils/types.ts

main 페이지에서 input 유효성 검사 기능 추가했습니다!

[feature] main 유효성 검사 기능 추가

---

client/src/Components/CategoryTag/index.ts
client/src/Model/MainModel.ts
client/src/View/MainView/index.ts

1. main input에서 날짜 입력칸을 3개로 수정하면서 데이터가 추가되지 않던 버그 수정했습니다.
2. input에서 카테고리를 DB에 없는 것을 입력하면 미분류로 지정하였습니다.
3. history를 추가할 경우 validation 초기화가 안되는 버그 수정하였습니다.
4. main input 금액 입력할 때 comma 추가하였습니다.

[feature] main 컴포넌트 약간의 버그 수정

---

client/src/Components/Header/index.ts
client/src/Components/Header/styles.scss

페이지 이동할 때 해당 페이지 아이콘을 활성화(white로)하는 기능 추가했습니다

[feature] header 아이콘 페이지에 맞게 활성화

---

client/src/Components/Calendar/index.ts
client/src/Components/Header/index.ts
client/src/Components/Main/index.ts
client/src/assets/dummy.ts
client/src/utils/types.ts

- 더미데이터 연동하는 mainModel 구독하여 렌더링 테스트
- 일부 타입 수정

[feature] Calendar 더미데이터 연동 작업 모델 구독 구현

---

server/api/routes/category.ts
server/controllers/category.controller.ts
server/entities/UserCategory.ts
server/repositories/category.repository.ts
server/services/category.services.ts
server/tsconfig.json
server/types/express.d.ts
server/types/types.ts

- 카테고리 라우트 설정 완료
- 카테고리 컨트롤러 작성
- 카테고리 서비스 로직 작성
- 카테고리 엔티티 및 레포지토리 데이터 로직 작성
- `express.d.ts` 예시 파일 추가 (아직 내용 추가 안 됨)

[feature] 카테고리 API 기본 코드 베이스 및 기본 로직 구현

---

server/api/routes/payment.ts
server/controllers/payment.controller.ts
server/repositories/payment.repository.ts
server/services/payment.services.ts
server/types/types.ts

- 결제수단 라우트 설정 완료
- 결제수단 컨트롤러 작성
- 결제수단 서비스 로직 작성
- 결제수단 엔티티 및 레포지토리 데이터 로직 작성

[feature] 결제수단 API 기본 코드 베이스 및 기본 로직 구현 

---

client/src/Components/Calendar/index.ts
client/src/Components/Header/index.ts
client/src/Components/Main/index.ts
client/src/Components/Main/styles.scss
client/src/Core/Component.ts
client/src/Core/Router.ts
client/src/Core/diffing.ts
client/src/Model/MainModel.ts
client/src/main.ts
client/src/utils/helper.ts
client/src/utils/types.ts

- diffing 알고리즘 적용
- DOMParser를 이용한 From template literal To DOM 변환
- 에러핸들링 처리
PS) 페어프로그래밍으로 진행

[feature] diffing 알고리즘을 적용한 부분 렌더링 구현

---

server/api/routes/history.ts
server/controllers/history.controller.ts
server/repositories/history.repository.ts
server/services/history.services.ts
server/types/types.ts

* it closes #36 
* history CRUD 
* 컨트롤러에서 Error catch 시 `ok: false` Response 전송

[feature] history API 작성

---

server/api/middlewares/auth.middleware.ts
server/api/routes/category.ts
server/api/routes/payment.ts
server/api/routes/user.ts
server/config/index.ts
server/controllers/category.controller.ts
server/controllers/payment.controller.ts
server/controllers/user.controller.ts
server/entities/RefreshToken.ts
server/entities/User.ts
server/package-lock.json
server/package.json
server/repositories/refreshToken.repository.ts
server/repositories/user.repository.ts
server/services/token.services.ts
server/services/user.services.ts
server/tsconfig.json
server/types/express.d.ts
server/types/types.ts
server/utils/getPayload.ts
server/utils/jwtAuth.ts

- Refresh 토큰 관련 Entity 설정
- User Entity 토큰 추가됨에 따라 재설정
- github를 이용해 Oauth 로그인 기능 추가
- Jwt를 이용한 유저 인증 및 토큰 발급 시스템 구현
PS) 페어 프로그래밍으로 진행해씁니드아

[feature] Oauth 관련 로그인 처리 및 미들웨어 적용

---

client/package-lock.json
client/package.json
client/src/api/auth.ts
client/src/api/category.ts
client/src/api/payment.ts
client/webpack.config.js
server/api/middlewares/auth.middleware.ts
server/controllers/category.controller.ts
server/loaders/express.loader.ts
server/package-lock.json
server/package.json

- 프론트단에서 API 호출 테스트 진행
- 백엔드 서버 cors 설정
- 기타 오류 수정
PS. 페어 프로그래밍으로 진행했습니다 :)

[feature] 백엔드 API 프론트단에 연결

---

server/controllers/category.controller.ts
server/controllers/history.controller.ts
server/controllers/payment.controller.ts
server/controllers/user.controller.ts
server/services/category.services.ts
server/services/history.services.ts
server/services/payment.services.ts
server/services/token.services.ts
server/services/user.services.ts

- typedi Container, Service 데코레이터 패턴을 이용해 의존성 관리 및 주입
- 오류없이 잘 되는 듯? 합니다
- 뭐가 더 좋아진 건진 모르겠습니다(?)

[refactor] typedi를 이용한 서비스-컨트롤로 간 의존성 주입 작성

---

server/config/index.ts
server/controllers/category.controller.ts
server/controllers/payment.controller.ts
server/controllers/user.controller.ts
server/loaders/express.loader.ts
server/services/history.services.ts
server/services/user.services.ts
server/utils/getPayload.ts
server/utils/helper.ts

- 로직에서 선언된 options와 같은 속성들 모두 config 파일에 분리하여 작성
- 일부 URL 등 노출에 민감한 속성은 env 파일을 이용하여 숨김처리 진행
- 컨트롤러 및 서비스에서 반복적으로 수행되는 기능은 정리하여 헬퍼 함수화
- 사용하지 않는 파일 모두 제거

[refactor] options 및 반복 기능 헬퍼 함수화

---

client/src/Components/CategoryIcon/index.ts
client/src/Components/CategoryIcon/styles.scss
client/src/Components/User/index.ts
client/src/Components/User/styles.scss
client/src/Components/UserCategory/index.ts
client/src/Components/UserCategory/styles.scss
client/src/Model/CategoryModel.ts
client/src/View/UserView/index.ts
client/src/api/category.ts
client/src/assets/svgIcons.ts
client/src/utils/types.ts
server/repositories/category.repository.ts

[feat] 카테고리 API 연동

---

client/src/Components/PaymentElem/index.ts
client/src/Components/PaymentElem/styles.scss
client/src/Components/User/index.ts
client/src/Components/UserPayment/index.ts
client/src/Components/UserPayment/styles.scss
client/src/Model/PaymentsModel.ts
client/src/api/payment.ts
client/src/utils/types.ts

* it closes #59 
클라이언트에서 지불 수단 API 연동했습니다~~

[feature] 지불 수단 API 연동

---

client/src/Components/InputBar/index.ts
client/src/Components/InputBar/styles.scss
client/src/Core/Component.ts
server/repositories/history.repository.ts
server/types/types.ts

관련이슈 : #74 #75 
- 프로퍼티 오타 문제 : `createAt` -> `createdAt` 으로 변경
- 컴포넌트 코어 클래스 setState 비교 로직 주석처리
- `inputBar` 컴포넌트 포지션 수정

[feature] History 날짜 제대로 삽입되지 않던 문제 수정

---

client/src/Components/CategoryDropdown/index.ts
client/src/Components/CategoryDropdown/styles.scss
client/src/Components/InputBar/index.ts
client/src/Components/InputBar/styles.scss
server/services/category.services.ts

- 카테고리 태그 슬라이더로 선택할 수 있도록 구현
- 커스텀 이벤트 디스패치로 등록 관리
- 기존 Inputbar 컴포넌트 연동을 위해 일부 수정

[feature] category dropdown 컴포넌트 작성 및 입력창과 연동

---

client/src/Components/CategoryTag/index.ts
client/src/Components/DonutChart/index.ts
client/src/Components/HistoryCategoryCard/index.ts
client/src/Components/HistoryDayCard/index.ts
client/src/Components/HistoryList/index.ts
client/src/Components/LineChart/index.ts
client/src/Components/Main/index.ts
client/src/Controller/ChartController.ts
client/src/utils/types.ts

관련 이슈 : #68 
* 차트와 메인에 카테고리 태그 색상 추가
* 사용자가 지운 카테고리일 경우 `#d2d2d2` 색상값 고정입니다
* 차트의 svg에도 색상 값 추가했습니다.
+ 제가 이슈 번호를 착각해서 커밋이 #71로 갔씁니다ㅠㅠ

[feature] 차트에 카테고리 색상 추가

---

client/src/Components/CategoryDropdown/index.ts
client/src/Components/CategoryDropdown/styles.scss
client/src/Components/InputBar/index.ts
client/src/Components/InputBar/styles.scss
client/src/Components/PaymentDropdown/index.ts
client/src/Components/PaymentDropdown/styles.scss

- 결제수단 드랍다운 작성
- 아직 디자인은 반영되지 않았습니다
- 특정 조건에서 선택이 안 되는 버그가 있는데 특정 조건이 뭔지 알아내서 디버그 해야할 듯 합니다

[feature] 결제수단 드랍다운 컴포넌트 작성

---

client/src/Components/CategoryDropdown/index.ts
client/src/Components/DropDown/index.ts
client/src/Components/DropDown/styles.scss
client/src/Components/HistoryDayCard/index.ts
client/src/Components/HistoryList/index.ts
client/src/Components/InputBar/index.ts
client/src/Components/Main/index.ts
client/src/Components/PaymentDropdown/index.ts
client/src/Model/HistoryModel.ts
client/src/api/history.ts
client/src/utils/helper.ts
client/src/utils/types.ts

관련 이슈 : #79 
* history update api 연동
* history delete api 연동
* 내역 수정하기 누르면 내역 추가하기 창을 수정하기로 변경

[feature] Histroy Update/Delete API 연동

---

client/src/api/history.ts
server/api/routes/history.ts
server/controllers/history.controller.ts
server/repositories/history.repository.ts
server/services/history.services.ts

* it closes #83 
월별 카테고리 지출 추이를 가져오는 API 서버와 클라이언트 양쪽 모두 작성했습니다.

[feature] history stat API 추가

---

client/src/Components/CategoryDropdown/index.ts
client/src/Components/CategoryDropdown/styles.scss
client/src/Components/CategoryTag/styles.scss
client/src/Components/HistoryDayCard/index.ts
client/src/Components/HistoryList/styles.scss
client/src/Components/InputBar/index.ts
client/src/Components/InputBar/styles.scss
client/src/Components/Main/index.ts
client/src/Components/PaymentDropdown/index.ts
client/src/Components/PaymentDropdown/styles.scss
client/src/Core/Component.ts
client/src/scss/index.scss
client/src/scss/reset.scss
client/src/scss/theme.scss
client/src/utils/helper.ts

- 수정 시 제대로 입력되지 않는 버그 수정
- 입력 시 디폴트 날짜값으로 계속 생성되는 문제 수정
- 관련 이벤트 중복 처리되어 계속 누적되는 문제 수정
- 일부 동일한 기능 메서드 묶어서 처리하도록 변경
- 인풋창 디자인 변경
- 날짜입력 - 개별 키보드 입력에서 브라우저 date picker를 사용하도록 변경

[feature] 메인페이지 인풋창 디자인 초안 및 CRUD 관련 버그 수정

---

client/src/Components/DropDown/index.ts
client/src/Components/Header/index.ts
client/src/Components/HistoryCategoryCard/index.ts
client/src/Components/HistoryCategoryCard/styles.scss
client/src/Components/HistoryDayCard/index.ts
client/src/Components/HistoryList/index.ts
client/src/Components/HistoryList/styles.scss
client/src/Components/InputBar/index.ts
client/src/Components/InputBar/styles.scss
client/src/Components/Main/index.ts
client/src/Components/PaymentDropdown/styles.scss
client/src/scss/animation.scss

- 드랍다운 관련 버그 수정 (참고: #88)
- 수정/삭제 기능 hover 이벤트에 추가로 등장하도록 기능 추가(모바일 고려)
- 드랍다운 관련 이벤트 전역 등록 시 헤더에서 관리하도록 수정

[bugfix] 드랍다운 관련 버그 및 이슈 해결 + 기능 추가

---

client/src/Components/Alerrt/index.ts
client/src/Components/Alerrt/styles.scss
client/src/Components/DropDown/index.ts
client/src/Components/Header/index.ts
client/src/Components/HistoryCategoryCard/index.ts
client/src/Components/HistoryCategoryCard/styles.scss
client/src/Components/HistoryDayCard/index.ts
client/src/Components/HistoryList/index.ts
client/src/Components/HistoryList/styles.scss
client/src/Components/InputBar/index.ts
client/src/Components/InputBar/styles.scss
client/src/Components/Main/index.ts
client/src/Components/PaymentDropdown/styles.scss
client/src/View/MainView/index.ts
client/src/scss/animation.scss

- 삭제 기능 클릭 시 Alert창 출력
- Alert에서 최종 삭제 클릭 시 삭제되도록 로직 변경
PS) 이전 이력 커밋이 딸려오는데 이전 PR을 머지하면 자동으로 사라질까요오?

[feature] 삭제 경고메시지를 위한 Alert 컴포넌트 구현

---

.gitignore
client/package-lock.json
client/package.json
client/src/api/auth.ts
client/src/api/category.ts
client/src/api/history.ts
client/src/api/payment.ts
client/src/api/user.ts
client/webpack.config.js
server/config/index.ts
server/ormconfig.ts
server/package-lock.json
server/package.json
server/tsconfig.json

- 배포를 위한 개발/프로덕션 환경 분리 세팅 진행
- 실제로 배포 띄워서 확인이 필요할 거 같습니다.

[feature] 개발/프로덕션 배포 환경 분리 진행

---

client/src/Components/LineChart/index.ts
client/src/Components/LineChart/styles.scss
client/src/Model/HistoryModel.ts
client/src/api/history.ts
client/src/utils/types.ts
server/api/routes/history.ts
server/controllers/history.controller.ts
server/repositories/history.repository.ts
server/services/history.services.ts
server/types/types.ts

* it closes #97 
수입 카테고리도 라인 차트로 출력할 수 있습니다!
+ line chart animation 아주 조금 수정했습니다.

[feature] 수입 카테고리도 라인 차트로 출력

---

client/src/Components/Loading/index.ts
client/src/Components/Loading/styles.scss
client/src/View/UserView/index.ts

관련 이슈 : #95 
로딩 컴포넌트 추가~~~ 볼 일 없을 것같아서 gif라도...

[feature] 로딩 컴포넌트 추가

---

client/src/Components/Header/styles.scss
client/src/scss/index.scss

[feature] 반응형 디자인 설계

---

client/src/Components/Calendar/styles.scss
client/src/Components/CategoryTag/styles.scss
client/src/Components/HistoryList/styles.scss
client/src/Components/InputBar/styles.scss
client/src/Components/Main/styles.scss
client/src/Components/PriceBar/styles.scss
client/src/Controller/CalendarController.ts
client/src/View/CalendarView/styles.scss

관련 이슈: #95 
메인과 캘린더 페이지 반응형 추가했습니다.

[feature] 메인, 캘린더 페이지 반응형 구현

---

client/src/Components/UserCategory/index.ts

* it closes #104 
유저 카테고리 생성시 랜덤 색상 오류 해결

[bugfix] 유저 카테고리 생성시 랜덤 색상 오류 해결

---

client/src/Components/DonutChart/styles.scss
client/src/Components/Header/styles.scss
client/src/Components/PaymentElem/styles.scss
client/src/Components/User/styles.scss
client/src/Components/UserCategory/styles.scss
client/src/Components/UserPayment/styles.scss
client/src/Controller/ChartController.ts
client/src/View/ChartsView/styles.scss
client/src/View/UserView/styles.scss
client/src/scss/animation.scss

- 유저페이지 반응형 디자인 설계 완료
- 카드 디자인 변경

[feature] 유저페이지 반응형 디자인 설계

---

client/src/Components/HistoryDayCard/index.ts
client/src/Components/HistoryDayCard/styles.scss
client/src/Components/HistoryList/styles.scss
client/src/Components/InputBar/styles.scss
client/src/Components/LineChart/index.ts
client/src/Components/Main/index.ts
client/src/Components/Main/styles.scss
client/src/Components/User/styles.scss
client/src/Components/UserPayment/index.ts
client/src/Core/Component.ts
client/src/Model/HistoryModel.ts
client/src/main.ts
client/src/scss/animation.scss
client/src/utils/types.ts
client/webpack.config.js

- 자체 QA 진행 후 버그 수정 및 세부 디자인 수정

refactor: 기타 버그 및 오류, 세부 디자인 수정
